apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: # deployment desired state
  replicas: 3 # 동일한 pod template의 pod를 3개 복제본으로 생성
  selector:
    matchLabels:
      app: nginx
  template: # pod의 template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80 # container 내부 port